### ISSUE TITLE
Backdrop functionality

### ISSUE THREAD

**Issue by Eothred** [Rudloff/piwigo-chromecast#3]
Sorry if this is an ignorant question. Is there any possibility of adding a "backdrop functionality" from Piwigo, so that you can select a folder to show on the Chromecast when it is in 'standby mode'? At the moment I can only select albums from my Google account it seems.

**Comment by Rudloff** [comment]
Sorry but I don't think the JS API allows to control the backdrop (it was announced last year, but I couldn't find anything about it in the doc).
