### ISSUE TITLE
no directory in zip file

### ISSUE THREAD

**Issue by plegall** [Rudloff/piwigo-chromecast#4]
Hi,

The zip file, available on Piwigo.org, does not contain any "root" directory. There should be one, and considering the source code, it should be "chromecast" (case-sensitive)

**Comment by plegall** [comment]
On http://piwigo.org/ext/extension_svn.php?eid=764 I have configured Github as repository URL and set the root directory in archive. You will need to use the "Git" option when adding a new revision of the plugin. Even if there is no change in your code, a new revision would be useful to fix this deployment issue :-)

**Comment by Rudloff** [comment]
Thanks. I published a new release from Git so it should be OK now.
